// GENERATED by scripts/sync-pro-catalog.mjs — do not edit by hand.
// Source: lib/spinner-patterns.ts in the pro-d2 repo. Refresh with `pnpm pro:sync`.

import type { SpinnerColor, SpinnerAnimation } from "@/components/pixel-spinner";

export type ProSpinner = {
  name: string;
  color: SpinnerColor;
  animation: SpinnerAnimation | null;
  /** "pro" is the hand-drawn 4x4 set, "premium" the curated generated subset. */
  shelf: "pro" | "premium";
  pattern: {
    size: number | null;
    rows: number | null;
    cols: number | null;
    interval: number | null;
    frames: number[][];
  };
};

export const PRO_SPINNERS: ProSpinner[] = [
  {
    "name": "pro-1",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 130,
      "frames": [
        [
          8
        ],
        [
          4,
          8
        ],
        [
          0,
          4,
          8,
          12
        ],
        [
          0,
          4,
          5,
          8,
          9,
          12
        ],
        [
          0,
          4,
          5,
          6,
          8,
          9,
          10,
          12
        ],
        [
          0,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12
        ],
        [
          0,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          15
        ],
        [
          5,
          6,
          9,
          10
        ],
        [
          0,
          3,
          5,
          6,
          9,
          10,
          12,
          15
        ],
        [
          0,
          3,
          5,
          6,
          9,
          10,
          12,
          15
        ],
        [
          2,
          4,
          5,
          6,
          9,
          10,
          11,
          13
        ],
        [
          1,
          5,
          6,
          7,
          8,
          9,
          10,
          14
        ],
        [
          0,
          3,
          5,
          6,
          9,
          10,
          12,
          15
        ]
      ]
    }
  },
  {
    "name": "pro-2",
    "color": "crimson",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 120,
      "frames": [
        [
          13,
          14
        ],
        [
          9,
          10,
          12,
          15
        ],
        [
          1,
          2
        ],
        [
          0,
          3,
          5,
          6
        ]
      ]
    }
  },
  {
    "name": "pro-3",
    "color": "hotpink",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 2,
      "interval": 110,
      "frames": [
        [
          0,
          2,
          4,
          6
        ],
        [
          0,
          2,
          3,
          4,
          5,
          6
        ],
        [
          1,
          3,
          5,
          7
        ],
        [
          1,
          2,
          3,
          4,
          5,
          7
        ]
      ]
    }
  },
  {
    "name": "pro-4",
    "color": "violet",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 2,
      "interval": 100,
      "frames": [
        [
          0
        ],
        [
          1
        ],
        [
          3
        ],
        [
          5
        ],
        [
          7
        ],
        [
          6
        ],
        [
          4
        ],
        [
          2
        ]
      ]
    }
  },
  {
    "name": "pro-5",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 110,
      "frames": [
        [
          0
        ],
        [
          1,
          4
        ],
        [
          5
        ],
        [
          6,
          9,
          10
        ],
        [
          15
        ],
        [
          11,
          14,
          15
        ],
        [
          7,
          10,
          11,
          13,
          14,
          15
        ],
        [
          3,
          6,
          7,
          9,
          10,
          11,
          12,
          13,
          14,
          15
        ],
        [
          2,
          3,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15
        ],
        [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15
        ]
      ]
    }
  },
  {
    "name": "pro-6",
    "color": "crimson",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 2,
      "interval": 130,
      "frames": [
        [
          2,
          3,
          4,
          5
        ],
        [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7
        ],
        [
          0,
          1,
          6,
          7
        ],
        [
          2,
          3,
          4,
          5
        ]
      ]
    }
  },
  {
    "name": "pro-7",
    "color": "hotpink",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 160,
      "frames": [
        [
          15
        ],
        [
          10,
          11,
          14,
          15
        ],
        [
          5,
          6,
          9,
          10
        ],
        [
          0,
          1,
          4,
          5
        ],
        [
          0
        ],
        [],
        [
          8,
          9,
          12,
          13
        ],
        [
          5,
          6,
          8,
          9,
          10,
          12,
          13
        ],
        [
          2,
          3,
          5,
          6,
          7,
          9,
          10
        ],
        [],
        []
      ]
    }
  },
  {
    "name": "pro-8",
    "color": "violet",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 2,
      "interval": 120,
      "frames": [
        [
          0,
          1
        ],
        [
          2,
          3
        ],
        [
          4,
          5
        ],
        [
          6,
          7
        ],
        [
          4,
          5
        ],
        [
          2,
          3
        ]
      ]
    }
  },
  {
    "name": "pro-9",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 2,
      "interval": 100,
      "frames": [
        [
          6
        ],
        [
          4
        ],
        [
          3
        ],
        [
          1
        ],
        [
          0
        ],
        [
          2
        ],
        [
          5
        ],
        [
          7
        ]
      ]
    }
  },
  {
    "name": "pro-10",
    "color": "crimson",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 2,
      "interval": 110,
      "frames": [
        [
          0
        ],
        [
          2
        ],
        [
          4
        ],
        [
          6
        ],
        [
          1
        ],
        [
          3
        ],
        [
          5
        ],
        [
          7
        ]
      ]
    }
  },
  {
    "name": "pro-11",
    "color": "hotpink",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 2,
      "interval": 110,
      "frames": [
        [
          2,
          3,
          4,
          5
        ],
        [
          0,
          1,
          6,
          7
        ],
        [],
        [
          2,
          3,
          4,
          5
        ],
        [
          0,
          1,
          6,
          7
        ],
        [],
        [],
        []
      ]
    }
  },
  {
    "name": "pro-12",
    "color": "violet",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 2,
      "interval": 160,
      "frames": [
        [
          5,
          6
        ],
        [
          3,
          4
        ],
        [
          1,
          2
        ],
        [
          0
        ],
        [
          0,
          1
        ],
        [
          2,
          3,
          4
        ],
        [
          5,
          6
        ],
        [
          4,
          7
        ]
      ]
    }
  },
  {
    "name": "pro-44",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 3,
      "interval": 120,
      "frames": [
        [
          1
        ],
        [
          4
        ],
        [
          7
        ],
        [
          10
        ],
        [
          9,
          11
        ],
        [
          8
        ],
        [
          5,
          6
        ],
        [
          2,
          3
        ],
        [
          0,
          2
        ]
      ]
    }
  },
  {
    "name": "pro-13",
    "color": "crimson",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 130,
      "frames": [
        [
          1,
          5,
          6,
          7,
          8,
          9,
          10,
          14
        ],
        [
          2,
          4,
          5,
          6,
          9,
          10,
          11,
          13
        ],
        [
          0,
          3,
          5,
          6,
          9,
          10,
          12,
          15
        ],
        [
          1,
          5,
          6,
          7,
          8,
          9,
          10,
          14
        ],
        [
          0,
          3,
          12,
          15
        ],
        [
          2,
          4,
          11,
          13
        ],
        [
          1,
          7,
          8,
          14
        ]
      ]
    }
  },
  {
    "name": "pro-14",
    "color": "hotpink",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 110,
      "frames": [
        [
          0
        ],
        [
          0,
          15
        ],
        [
          1,
          14
        ],
        [
          2,
          13
        ],
        [
          12
        ],
        [
          4,
          11
        ],
        [
          5,
          10
        ],
        [
          5,
          6,
          9,
          10
        ],
        [
          0,
          15
        ],
        [
          3,
          12
        ]
      ]
    }
  },
  {
    "name": "pro-15",
    "color": "violet",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 160,
      "frames": [
        [
          2,
          4,
          5,
          6,
          9,
          10,
          11,
          13
        ],
        [
          0,
          3,
          5,
          6,
          9,
          10,
          12,
          15
        ],
        [
          5,
          6,
          9,
          10
        ],
        [
          1,
          5,
          6,
          7,
          8,
          9,
          10,
          14
        ]
      ]
    }
  },
  {
    "name": "pro-45",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 130,
      "frames": [
        [
          14
        ],
        [
          13,
          14
        ],
        [
          12,
          13,
          14,
          15
        ],
        [
          9,
          10,
          12,
          13,
          14,
          15
        ],
        [
          5,
          6,
          9,
          10,
          12,
          13,
          14,
          15
        ],
        [
          1,
          2,
          5,
          6,
          9,
          10,
          12,
          13,
          14,
          15
        ],
        [
          0,
          1,
          2,
          3,
          5,
          6,
          9,
          10,
          12,
          13,
          14,
          15
        ],
        [
          5,
          6,
          9,
          10
        ],
        [
          0,
          3,
          5,
          6,
          9,
          10,
          12,
          15
        ],
        [
          0,
          3,
          5,
          6,
          9,
          10,
          12,
          15
        ],
        [
          2,
          4,
          5,
          6,
          9,
          10,
          11,
          13
        ],
        [
          1,
          5,
          6,
          7,
          8,
          9,
          10,
          14
        ],
        [
          0,
          3,
          5,
          6,
          9,
          10,
          12,
          15
        ]
      ]
    }
  },
  {
    "name": "pro-16",
    "color": "crimson",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 4,
      "interval": 160,
      "frames": [
        [
          0
        ],
        [
          5
        ],
        [
          8
        ],
        [
          3
        ],
        [
          6
        ],
        [
          11
        ],
        [
          5
        ]
      ]
    }
  },
  {
    "name": "pro-17",
    "color": "hotpink",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 3,
      "interval": 140,
      "frames": [
        [
          6
        ],
        [
          3,
          4,
          6,
          7
        ],
        [
          0,
          1,
          2,
          4,
          5,
          8
        ],
        [
          1,
          2,
          4,
          5
        ],
        [
          0,
          2,
          3,
          4,
          6,
          7,
          8
        ]
      ]
    }
  },
  {
    "name": "pro-18",
    "color": "violet",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 3,
      "interval": 140,
      "frames": [
        [
          1,
          3,
          5,
          7
        ],
        [
          0,
          2,
          6,
          8
        ],
        [
          0,
          2,
          4,
          6,
          8
        ],
        [
          0,
          2,
          4,
          6
        ],
        [
          0,
          2,
          4
        ],
        [
          2,
          4,
          8
        ],
        [
          4,
          6,
          8
        ],
        [
          0,
          4,
          6
        ]
      ]
    }
  },
  {
    "name": "pro-19",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 5,
      "interval": 120,
      "frames": [
        [
          0
        ],
        [
          1,
          5
        ],
        [
          2,
          6,
          10
        ],
        [
          3,
          7,
          11
        ],
        [
          4,
          8,
          12
        ],
        [
          9,
          13
        ],
        [
          14
        ],
        [
          9,
          13
        ],
        [
          4,
          8,
          12
        ],
        [
          3,
          7,
          11
        ],
        [
          2,
          6,
          10
        ],
        [
          1,
          5
        ]
      ]
    }
  },
  {
    "name": "pro-20",
    "color": "crimson",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 5,
      "interval": 120,
      "frames": [
        [
          9
        ],
        [
          8
        ],
        [
          7
        ],
        [
          6
        ],
        [
          5
        ],
        [
          0,
          10
        ],
        [
          11
        ],
        [
          1,
          12
        ],
        [
          2,
          13
        ],
        [
          3,
          14
        ],
        [
          4,
          14
        ]
      ]
    }
  },
  {
    "name": "pro-21",
    "color": "hotpink",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 5,
      "interval": 120,
      "frames": [
        [
          0
        ],
        [
          14
        ],
        [
          1
        ],
        [
          13
        ],
        [
          2,
          12
        ],
        [
          3,
          11
        ],
        [
          4,
          10
        ],
        [
          5,
          9
        ]
      ]
    }
  },
  {
    "name": "pro-22",
    "color": "violet",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 6,
      "interval": 160,
      "frames": [
        [
          0,
          2,
          4,
          7,
          9,
          11,
          12,
          14,
          16
        ],
        [
          1,
          3,
          5,
          6,
          8,
          10,
          13,
          15,
          17
        ]
      ]
    }
  },
  {
    "name": "pro-23",
    "color": "blue",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 6,
      "interval": 160,
      "frames": [
        [
          14,
          15
        ],
        [
          8,
          9,
          13,
          16
        ],
        [
          2,
          3,
          7,
          10,
          12,
          17
        ],
        [
          8,
          9,
          13,
          16
        ]
      ]
    }
  },
  {
    "name": "pro-24",
    "color": "crimson",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 6,
      "interval": 160,
      "frames": [
        [
          14,
          15
        ],
        [
          8,
          9,
          13,
          16
        ],
        [
          2,
          3,
          7,
          10,
          12,
          17
        ],
        [
          1,
          4,
          6,
          11
        ],
        [
          0,
          5
        ],
        []
      ]
    }
  },
  {
    "name": "pro-25",
    "color": "hotpink",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 6,
      "interval": 130,
      "frames": [
        [
          6,
          11
        ],
        [
          0,
          5,
          7,
          10,
          12,
          17
        ],
        [
          1,
          4,
          8,
          9,
          13,
          16
        ],
        [
          2,
          3,
          8,
          9,
          14,
          15
        ],
        [
          1,
          4,
          8,
          9,
          13,
          16
        ],
        [
          0,
          5,
          7,
          10,
          12,
          17
        ],
        [
          6,
          11
        ],
        []
      ]
    }
  },
  {
    "name": "pro-26",
    "color": "violet",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 6,
      "interval": 110,
      "frames": [
        [
          2,
          5,
          6,
          9,
          14,
          17
        ],
        [
          0,
          3,
          7,
          10,
          12,
          15
        ],
        [
          1,
          4,
          8,
          11,
          13,
          16
        ]
      ]
    }
  },
  {
    "name": "pro-27",
    "color": "blue",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 5,
      "interval": 100,
      "frames": [
        [
          15,
          16
        ],
        [
          11
        ],
        [
          7
        ],
        [
          2
        ],
        [
          3
        ],
        [
          8
        ],
        [
          14
        ],
        [
          18,
          19
        ],
        [
          14
        ],
        [
          8
        ],
        [
          3
        ],
        [
          2
        ],
        [
          7
        ],
        [
          11
        ]
      ]
    }
  },
  {
    "name": "pro-28",
    "color": "crimson",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 6,
      "interval": 100,
      "frames": [
        [
          6
        ],
        [
          7
        ],
        [
          2
        ],
        [
          9
        ],
        [
          15
        ],
        [
          10
        ],
        [
          11
        ],
        []
      ]
    }
  },
  {
    "name": "pro-29",
    "color": "hotpink",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 3,
      "interval": 200,
      "frames": [
        [
          0,
          1,
          2,
          3,
          4,
          5
        ],
        [
          0,
          1,
          2,
          3,
          4,
          5,
          7
        ],
        [
          3,
          4,
          5,
          7,
          9,
          10,
          11
        ],
        [
          4,
          7,
          9,
          10,
          11
        ],
        [
          6,
          7,
          8,
          9,
          10,
          11
        ],
        [
          6,
          7,
          8,
          9,
          10,
          11
        ]
      ]
    }
  },
  {
    "name": "pro-30",
    "color": "violet",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 140,
      "frames": [
        [
          1,
          2,
          3,
          6,
          7,
          11,
          12
        ],
        [
          1,
          2,
          3,
          6,
          7,
          9,
          11
        ],
        [
          1,
          2,
          3,
          6,
          7,
          11
        ],
        [
          1,
          2,
          3,
          6,
          7,
          8,
          11,
          13
        ]
      ]
    }
  },
  {
    "name": "pro-31",
    "color": "blue",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 140,
      "frames": [
        [
          12
        ],
        [
          9
        ],
        [
          1,
          2,
          3,
          6,
          7,
          11
        ],
        [
          8,
          13
        ]
      ]
    }
  },
  {
    "name": "pro-32",
    "color": "crimson",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 150,
      "frames": [
        [
          1,
          4,
          5,
          6,
          9,
          10,
          11,
          14
        ],
        [
          0,
          1,
          4,
          5,
          6,
          9,
          10,
          11,
          14,
          15
        ],
        [
          2,
          3,
          5,
          6,
          7,
          8,
          9,
          10,
          12,
          13
        ],
        [
          0,
          1,
          4,
          5,
          6,
          9,
          10,
          11,
          14,
          15
        ],
        [
          2,
          3,
          5,
          6,
          7,
          8,
          9,
          10,
          12,
          13
        ],
        [
          5,
          6,
          9,
          10
        ],
        [
          2,
          5,
          6
        ],
        [
          9,
          10,
          14
        ]
      ]
    }
  },
  {
    "name": "pro-33",
    "color": "hotpink",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 3,
      "interval": 140,
      "frames": [
        [
          0,
          1,
          2
        ],
        [
          4
        ],
        [
          7
        ],
        [
          9,
          10,
          11
        ],
        [
          3,
          5,
          6,
          8
        ],
        [
          0,
          1,
          2,
          3,
          5,
          6,
          8,
          9,
          10,
          11
        ],
        [
          1
        ]
      ]
    }
  },
  {
    "name": "pro-34",
    "color": "violet",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 170,
      "frames": [
        [
          0,
          1,
          2,
          3,
          4,
          6,
          7,
          8,
          12,
          16,
          17,
          18,
          20,
          21,
          22,
          23,
          24
        ],
        [
          3,
          8,
          9,
          10,
          11,
          12,
          15,
          16,
          17,
          21,
          22
        ],
        [
          0,
          4,
          5,
          6,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          18,
          19,
          20,
          24
        ],
        [
          7,
          11,
          12,
          13,
          17
        ]
      ]
    }
  },
  {
    "name": "pro-35",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 150,
      "frames": [
        [
          0,
          3
        ],
        [
          1,
          2
        ],
        [
          5,
          6
        ],
        [
          9,
          10
        ],
        [
          13,
          14
        ],
        [
          12,
          15
        ],
        [
          13,
          14
        ],
        [
          12,
          15
        ],
        [
          9,
          10
        ],
        [
          5,
          6
        ],
        [
          1,
          2
        ],
        [
          0,
          3
        ],
        [
          1,
          2
        ]
      ]
    }
  },
  {
    "name": "pro-36",
    "color": "crimson",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 120,
      "frames": [
        [
          5,
          6,
          9,
          10
        ],
        [
          0
        ],
        [
          1,
          4
        ],
        [
          11,
          14
        ],
        [
          15
        ],
        [],
        [
          5,
          6,
          9,
          10
        ],
        [
          2,
          7
        ],
        [
          3
        ],
        [],
        [
          5,
          6,
          9,
          10
        ],
        [
          8,
          13
        ],
        [
          12
        ],
        []
      ]
    }
  },
  {
    "name": "pro-37",
    "color": "hotpink",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 110,
      "frames": [
        [
          13,
          14
        ],
        [
          9,
          10,
          12,
          15
        ],
        [
          5,
          6,
          8,
          11
        ],
        [
          1,
          2,
          4,
          7
        ],
        [
          0,
          3,
          5,
          6
        ],
        [
          4,
          7,
          9,
          10
        ],
        [
          8,
          11,
          13,
          14
        ],
        [
          3,
          6,
          10,
          15
        ],
        [
          2,
          5,
          9,
          14
        ],
        [
          1,
          4,
          8,
          13
        ],
        [
          0,
          5,
          9,
          12
        ],
        [
          1,
          6,
          10,
          13
        ],
        [
          1,
          6,
          10,
          13
        ],
        [
          2,
          7,
          11,
          14
        ],
        [
          4,
          7,
          9,
          10
        ]
      ]
    }
  },
  {
    "name": "pro-38",
    "color": "violet",
    "animation": "wavy",
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 110,
      "frames": [
        [
          8,
          9,
          13
        ],
        [
          1,
          4,
          5
        ],
        [
          2,
          6,
          7
        ],
        [
          10,
          11,
          14
        ],
        [
          8,
          9,
          13
        ]
      ]
    }
  },
  {
    "name": "pro-39",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 100,
      "frames": [
        [
          0,
          1,
          5,
          6,
          12,
          18,
          19,
          23,
          24
        ],
        [
          8,
          16
        ],
        [
          6,
          18
        ],
        [
          0
        ],
        [
          3,
          4,
          8,
          9
        ],
        [
          15,
          16,
          20,
          21
        ],
        [
          6,
          8,
          12,
          16,
          18
        ]
      ]
    }
  },
  {
    "name": "pro-40",
    "color": "crimson",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 110,
      "frames": [
        [
          6,
          8,
          12,
          16,
          18
        ],
        [
          4,
          20
        ],
        [
          0,
          24
        ],
        [
          7,
          11,
          12,
          13,
          17
        ],
        [
          3,
          5,
          19,
          21
        ],
        [
          1,
          9,
          15,
          23
        ],
        [
          3,
          5,
          19,
          21
        ]
      ]
    }
  },
  {
    "name": "pro-41",
    "color": "hotpink",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 110,
      "frames": [
        [],
        [
          3,
          9,
          19,
          23
        ],
        [
          3,
          9,
          12,
          15,
          19,
          21,
          23
        ],
        [
          1,
          3,
          5,
          9,
          12,
          15,
          19,
          21,
          23
        ],
        [
          7,
          11,
          12,
          13,
          17
        ],
        [
          2,
          6,
          7,
          8,
          10,
          11,
          12,
          13,
          14,
          16,
          17,
          18,
          22
        ],
        [
          0,
          4,
          20,
          24
        ]
      ]
    }
  },
  {
    "name": "pro-42",
    "color": "violet",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 110,
      "frames": [
        [
          12
        ],
        [
          7,
          11,
          12,
          13,
          17
        ],
        [
          2,
          6,
          7,
          8,
          10,
          11,
          12,
          13,
          14,
          16,
          17,
          18,
          22
        ],
        [
          0,
          4,
          20,
          24
        ]
      ]
    }
  },
  {
    "name": "pro-46",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 110,
      "frames": [
        [
          12
        ],
        [
          7,
          11,
          12,
          13,
          17
        ],
        [
          2,
          6,
          7,
          8,
          10,
          11,
          12,
          13,
          14,
          16,
          17,
          18,
          22
        ],
        [
          1,
          3,
          5,
          9,
          15,
          19,
          21,
          23
        ]
      ]
    }
  },
  {
    "name": "pro-47",
    "color": "crimson",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 110,
      "frames": [
        [
          2,
          6,
          8,
          10,
          14,
          16,
          18,
          22
        ],
        [
          12
        ],
        [
          1,
          3,
          5,
          9,
          15,
          19,
          21,
          23
        ],
        [
          6,
          8,
          16,
          18
        ],
        [
          7,
          11,
          12,
          13,
          17
        ]
      ]
    }
  },
  {
    "name": "pro-48",
    "color": "hotpink",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 110,
      "frames": [
        [
          7,
          11,
          13,
          17
        ],
        [],
        [
          6,
          8,
          12,
          16,
          18
        ],
        [
          2,
          10,
          14,
          22
        ],
        [
          0,
          4,
          20,
          24
        ],
        []
      ]
    }
  },
  {
    "name": "pro-49",
    "color": "violet",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 110,
      "frames": [
        [
          20
        ],
        [
          15,
          16,
          21
        ],
        [
          11,
          12,
          17
        ],
        [
          7,
          8,
          13
        ],
        [
          3,
          4,
          9
        ],
        [
          3,
          8,
          9
        ],
        [
          7,
          12,
          13
        ],
        [
          11,
          16,
          17
        ],
        [
          4,
          20
        ]
      ]
    }
  },
  {
    "name": "pro-50",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 3,
      "interval": 110,
      "frames": [
        [
          8,
          10
        ],
        [
          5,
          7,
          9
        ],
        [
          2,
          4,
          6
        ],
        [
          1,
          3
        ],
        [
          0
        ],
        [
          1,
          3
        ],
        [
          2,
          4,
          6
        ],
        [
          5,
          7,
          9
        ],
        [
          8,
          10
        ],
        [
          11
        ]
      ]
    }
  },
  {
    "name": "pro-51",
    "color": "crimson",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 5,
      "interval": 110,
      "frames": [
        [
          0,
          1,
          2,
          5,
          7,
          10,
          11,
          12
        ],
        [
          1,
          2,
          3,
          6,
          8,
          11,
          12,
          13
        ],
        [
          2,
          3,
          4,
          7,
          9,
          12,
          13,
          14
        ],
        [
          3,
          4,
          8,
          9,
          13,
          14
        ],
        [
          4,
          9,
          14
        ],
        [
          3,
          4,
          8,
          9,
          13,
          14
        ],
        [
          2,
          3,
          4,
          7,
          9,
          12,
          13,
          14
        ],
        [
          1,
          2,
          3,
          6,
          8,
          11,
          12,
          13
        ],
        [
          0,
          1,
          2,
          5,
          7,
          10,
          11,
          12
        ]
      ]
    }
  },
  {
    "name": "pro-52",
    "color": "hotpink",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 3,
      "interval": 110,
      "frames": [
        [
          0,
          1,
          2,
          3,
          5,
          6,
          7,
          8
        ],
        [
          3,
          4,
          5,
          6,
          8,
          9,
          10,
          11
        ],
        [
          6,
          7,
          8,
          9,
          11,
          12,
          13,
          14
        ],
        [
          9,
          10,
          11,
          12,
          13,
          14
        ],
        [
          12,
          13,
          14
        ],
        [
          9,
          10,
          11,
          12,
          13,
          14
        ],
        [
          6,
          7,
          8,
          9,
          11,
          12,
          13,
          14
        ],
        [
          3,
          4,
          5,
          6,
          8,
          9,
          10,
          11
        ],
        [
          0,
          1,
          2,
          3,
          5,
          6,
          7,
          8
        ]
      ]
    }
  },
  {
    "name": "pro-53",
    "color": "violet",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 110,
      "frames": [
        [
          0,
          1,
          5
        ],
        [
          0,
          1,
          5,
          6,
          7,
          11,
          12
        ],
        [
          0,
          1,
          5,
          6,
          7,
          11,
          12,
          13,
          17,
          18
        ],
        [
          0,
          1,
          5,
          6,
          7,
          11,
          12,
          13,
          17,
          18,
          19,
          23,
          24
        ],
        [
          12,
          13,
          17,
          18,
          19,
          23,
          24
        ],
        [
          19,
          23,
          24
        ],
        [
          14,
          18,
          22
        ],
        [
          9,
          13,
          17,
          21
        ],
        [
          4,
          8,
          12,
          16,
          20
        ],
        [
          3,
          7,
          11,
          15
        ],
        [
          2,
          6,
          10
        ],
        [
          1,
          5
        ],
        [
          0
        ]
      ]
    }
  },
  {
    "name": "pro-54",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 100,
      "frames": [
        [
          0
        ],
        [
          0,
          1,
          5
        ],
        [
          7,
          11
        ],
        [
          13,
          17
        ],
        [
          19,
          23
        ],
        [
          19,
          23,
          24
        ],
        [],
        [
          15,
          20,
          21
        ],
        [
          15,
          21
        ],
        [
          11,
          17
        ],
        [
          7,
          13
        ],
        [
          3,
          9
        ],
        [
          3,
          4,
          9
        ],
        []
      ]
    }
  },
  {
    "name": "pro-55",
    "color": "crimson",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 110,
      "frames": [
        [
          15,
          20,
          21
        ],
        [
          10,
          15,
          16,
          20,
          21,
          22
        ],
        [
          5,
          10,
          11,
          15,
          16,
          17,
          20,
          21,
          22,
          23
        ],
        [
          19,
          23,
          24
        ],
        [
          14,
          18,
          19,
          22,
          23,
          24
        ],
        [
          9,
          13,
          14,
          17,
          18,
          19,
          21,
          22,
          23,
          24
        ],
        [
          0
        ],
        [
          0,
          1,
          5
        ],
        [
          0,
          1,
          2,
          5,
          6,
          10
        ],
        [
          0,
          1,
          2,
          3,
          5,
          6,
          7,
          10,
          11,
          15
        ],
        [
          4
        ],
        [
          3,
          4,
          9
        ],
        [
          2,
          3,
          4,
          8,
          9,
          14
        ],
        [
          1,
          2,
          3,
          4,
          7,
          8,
          9,
          13,
          14,
          19
        ]
      ]
    }
  },
  {
    "name": "pro-43",
    "color": "hotpink",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 3,
      "interval": 120,
      "frames": [
        [
          13
        ],
        [
          10
        ],
        [
          7
        ],
        [
          4
        ],
        [
          1
        ],
        [
          0,
          2
        ],
        [
          3
        ],
        [
          5,
          6
        ],
        [
          8,
          9
        ],
        [
          11,
          12
        ],
        [
          12,
          14
        ]
      ]
    }
  },
  {
    "name": "pro-57",
    "color": "violet",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 130,
      "frames": [
        [
          7,
          11,
          12,
          13,
          17
        ],
        [
          6,
          8,
          12,
          16,
          18
        ],
        [
          2,
          10,
          14,
          22
        ],
        [
          0,
          4,
          20,
          24
        ]
      ]
    }
  },
  {
    "name": "pro-58",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 130,
      "frames": [
        [
          5,
          6,
          9,
          10
        ],
        [
          0,
          3,
          5,
          6,
          9,
          10,
          12,
          15
        ],
        [
          0,
          2,
          5,
          6,
          9,
          10,
          12,
          15
        ],
        [
          1,
          4,
          5,
          6,
          9,
          10,
          12,
          15
        ],
        [
          0,
          5,
          6,
          8,
          9,
          10,
          13,
          15
        ],
        [
          4,
          5,
          6,
          9,
          10,
          11,
          12,
          14
        ],
        [
          5,
          6,
          7,
          8,
          9,
          10,
          13,
          15
        ],
        [
          3,
          5,
          6,
          9,
          10,
          11,
          12,
          14
        ],
        [
          2,
          5,
          6,
          7,
          9,
          10,
          12,
          15
        ],
        [
          1,
          3,
          5,
          6,
          9,
          10,
          12,
          15
        ],
        [
          0,
          3,
          5,
          6,
          9,
          10,
          12,
          15
        ]
      ]
    }
  },
  {
    "name": "pro-59",
    "color": "crimson",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 100,
      "frames": [
        [
          5,
          6,
          15,
          16
        ],
        [
          0,
          5,
          6,
          15,
          16,
          20
        ],
        [
          12
        ],
        [
          8,
          9,
          18,
          19
        ],
        [
          4,
          8,
          9,
          18,
          19,
          24
        ],
        []
      ]
    }
  },
  {
    "name": "pro-60",
    "color": "hotpink",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 100,
      "frames": [
        [
          1,
          3,
          6,
          8
        ],
        [
          0,
          1,
          2,
          3,
          4,
          6,
          7,
          8
        ],
        [
          12
        ],
        [
          16,
          18,
          21,
          23
        ],
        [
          16,
          17,
          18,
          20,
          21,
          22,
          23,
          24
        ],
        []
      ]
    }
  },
  {
    "name": "pro-61",
    "color": "violet",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 130,
      "frames": [
        [
          4,
          9
        ],
        [
          9,
          14
        ],
        [
          2,
          7
        ],
        [
          8,
          13
        ],
        [
          1,
          4
        ],
        [
          6,
          9
        ],
        [
          5,
          8
        ],
        [
          6,
          9
        ],
        [
          2,
          5,
          7,
          8,
          10,
          13
        ]
      ]
    }
  },
  {
    "name": "pro-62",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 90,
      "frames": [
        [
          0,
          1,
          3,
          4,
          5,
          9,
          15,
          19,
          20,
          21,
          23,
          24
        ],
        [
          0,
          4,
          6,
          8,
          12,
          16,
          18,
          20,
          24
        ],
        [
          2,
          7,
          10,
          11,
          12,
          13,
          14,
          17,
          22
        ],
        [
          2,
          6,
          8,
          10,
          12,
          14,
          16,
          18,
          22
        ],
        [
          12
        ],
        [
          7,
          11,
          12,
          13,
          17
        ]
      ]
    }
  },
  {
    "name": "pro-64",
    "color": "crimson",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 130,
      "frames": [
        [
          1,
          2,
          7,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          17,
          22,
          23
        ],
        [
          2,
          3,
          5,
          7,
          10,
          11,
          12,
          13,
          14,
          17,
          19,
          21,
          22
        ],
        [
          0,
          2,
          4,
          10,
          12,
          14,
          20,
          22,
          24
        ],
        [
          0,
          4,
          12,
          20,
          24
        ],
        [
          1,
          3,
          5,
          9,
          15,
          19,
          21,
          23
        ]
      ]
    }
  },
  {
    "name": "pro-65",
    "color": "hotpink",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 130,
      "frames": [
        [
          1,
          3,
          4,
          6,
          9,
          11,
          12,
          14
        ],
        [
          0,
          2,
          5,
          7,
          8,
          10,
          13,
          15
        ],
        [],
        [
          4,
          6,
          9,
          11
        ],
        [
          2,
          5,
          7,
          8,
          10,
          13
        ]
      ]
    }
  },
  {
    "name": "pro-66",
    "color": "violet",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 90,
      "frames": [
        [
          2,
          6,
          8,
          10,
          12,
          14,
          16,
          18,
          22
        ],
        [
          7,
          11,
          12,
          13
        ],
        [
          7,
          12,
          17
        ],
        [
          7,
          11,
          12
        ],
        [
          13
        ]
      ]
    }
  },
  {
    "name": "pro-67",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 90,
      "frames": [
        [
          2,
          6,
          8,
          10,
          12,
          14,
          16,
          18,
          22
        ],
        [
          7,
          11,
          12,
          13
        ],
        [
          7,
          12,
          17
        ],
        [
          7,
          11,
          12
        ],
        [
          12
        ],
        [
          0,
          4,
          6,
          8,
          16,
          18,
          20,
          24
        ]
      ]
    }
  },
  {
    "name": "pro-68",
    "color": "crimson",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 100,
      "frames": [
        [
          2,
          6,
          8,
          10,
          12,
          14,
          16,
          18,
          22
        ],
        [
          7,
          11,
          12,
          13
        ],
        [
          7,
          12,
          17
        ],
        [
          7,
          11,
          12
        ],
        [
          12
        ],
        [
          0,
          4,
          6,
          8,
          12,
          16,
          18,
          20,
          24
        ],
        [
          2,
          7,
          10,
          11,
          12,
          13,
          14,
          17,
          22
        ]
      ]
    }
  },
  {
    "name": "pro-69",
    "color": "hotpink",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 90,
      "frames": [
        [
          2,
          6,
          8,
          10,
          12,
          14,
          16,
          18,
          22
        ],
        [
          7,
          11,
          12,
          13
        ],
        [
          7,
          12,
          17
        ],
        [
          7,
          11,
          12
        ],
        [
          12
        ],
        [
          0,
          4,
          6,
          8,
          12,
          16,
          18,
          20,
          24
        ],
        [
          2,
          7,
          10,
          11,
          12,
          13,
          14,
          17,
          22
        ],
        [
          0,
          1,
          3,
          4,
          5,
          9,
          15,
          19,
          20,
          21,
          23,
          24
        ]
      ]
    }
  },
  {
    "name": "pro-70",
    "color": "violet",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 110,
      "frames": [
        [
          0,
          4,
          6,
          8,
          12,
          16,
          18,
          20,
          24
        ],
        [
          2,
          6,
          8,
          10,
          12,
          14,
          16,
          18,
          22
        ],
        [
          2,
          7,
          10,
          11,
          12,
          13,
          14,
          17,
          22
        ],
        [
          0,
          1,
          3,
          4,
          5,
          9,
          15,
          19,
          20,
          21,
          23,
          24
        ]
      ]
    }
  },
  {
    "name": "pro-71",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 5,
      "cols": 5,
      "interval": 130,
      "frames": [
        [
          0,
          2,
          4,
          6,
          8,
          10,
          12,
          14,
          16,
          18,
          20,
          22,
          24
        ],
        [
          0,
          1,
          2,
          3,
          4,
          6,
          8,
          10,
          11,
          12,
          13,
          14,
          16,
          18,
          20,
          21,
          22,
          23,
          24
        ],
        [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24
        ],
        []
      ]
    }
  },
  {
    "name": "pro-72",
    "color": "crimson",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 160,
      "frames": [
        [
          15
        ],
        [
          10,
          11,
          14,
          15
        ],
        [
          5,
          6,
          9,
          10
        ],
        [
          0,
          1,
          4,
          5
        ],
        [
          0
        ]
      ]
    }
  },
  {
    "name": "pro-73",
    "color": "hotpink",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 100,
      "frames": [
        [
          0
        ],
        [
          0,
          15
        ],
        [
          1,
          14
        ],
        [
          2,
          13
        ],
        [
          12
        ],
        [
          4,
          11
        ],
        [
          5,
          10
        ],
        [
          5,
          6,
          9,
          10
        ],
        [
          0,
          3,
          5,
          6,
          9,
          10,
          12,
          15
        ]
      ]
    }
  },
  {
    "name": "pro-74",
    "color": "violet",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 4,
      "cols": 4,
      "interval": 140,
      "frames": [
        [
          12
        ],
        [
          8,
          9,
          13
        ],
        [
          6
        ],
        [
          2,
          6,
          7
        ],
        [
          3
        ],
        [
          3
        ]
      ]
    }
  },
  {
    "name": "pro-75",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": 3,
      "rows": null,
      "cols": null,
      "interval": 100,
      "frames": [
        [
          4
        ],
        [
          8
        ],
        [
          2
        ],
        [
          0
        ],
        [
          4
        ],
        [
          6
        ],
        [
          1
        ],
        [
          7
        ],
        [
          3
        ],
        [
          5
        ],
        [
          2,
          6
        ],
        [
          0,
          8
        ]
      ]
    }
  },
  {
    "name": "pro-76",
    "color": "crimson",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": 3,
      "rows": null,
      "cols": null,
      "interval": 120,
      "frames": [
        [
          2,
          4,
          5,
          6,
          7,
          8
        ],
        [
          0,
          3,
          4,
          6,
          7,
          8
        ],
        [
          0,
          1,
          2,
          4,
          5,
          8
        ],
        [
          0,
          1,
          2,
          3,
          4,
          6
        ],
        [
          0,
          4,
          8
        ],
        [
          2,
          4,
          6
        ]
      ]
    }
  },
  {
    "name": "pro-77",
    "color": "hotpink",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 7,
      "interval": 90,
      "frames": [
        [],
        [
          0,
          2,
          4,
          6,
          15,
          17,
          19
        ],
        [
          7,
          9,
          11,
          13
        ],
        [
          1,
          3,
          5,
          14,
          16,
          18,
          20
        ]
      ]
    }
  },
  {
    "name": "pro-78",
    "color": "violet",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 7,
      "interval": 90,
      "frames": [
        [],
        [
          1,
          3,
          5,
          14,
          16,
          18,
          20
        ],
        [
          7,
          9,
          11,
          13
        ],
        [
          0,
          2,
          4,
          6,
          15,
          17,
          19
        ]
      ]
    }
  },
  {
    "name": "pro-79",
    "color": "blue",
    "animation": null,
    "shelf": "pro",
    "pattern": {
      "size": null,
      "rows": 3,
      "cols": 7,
      "interval": 90,
      "frames": [
        [
          1,
          3,
          5,
          7,
          9,
          11,
          13,
          15,
          17,
          19
        ],
        [
          2,
          4,
          10,
          16,
          18
        ],
        [
          4,
          6,
          12,
          18,
          20
        ],
        [
          0,
          2,
          8,
          14,
          16
        ]
      ]
    }
  },
  {
    "name": "spiral-in-5",
    "color": "crimson",
    "animation": null,
    "shelf": "premium",
    "pattern": {
      "size": 5,
      "rows": null,
      "cols": null,
      "interval": 75,
      "frames": [
        [
          0
        ],
        [
          1
        ],
        [
          2
        ],
        [
          3
        ],
        [
          4
        ],
        [
          9
        ],
        [
          14
        ],
        [
          19
        ],
        [
          24
        ],
        [
          23
        ],
        [
          22
        ],
        [
          21
        ],
        [
          20
        ],
        [
          15
        ],
        [
          10
        ],
        [
          5
        ],
        [
          6
        ],
        [
          7
        ],
        [
          8
        ],
        [
          13
        ],
        [
          18
        ],
        [
          17
        ],
        [
          16
        ],
        [
          11
        ],
        [
          12
        ]
      ]
    }
  },
  {
    "name": "ring-4-cw",
    "color": "blue",
    "animation": null,
    "shelf": "premium",
    "pattern": {
      "size": 4,
      "rows": null,
      "cols": null,
      "interval": 110,
      "frames": [
        [
          0
        ],
        [
          1
        ],
        [
          2
        ],
        [
          3
        ],
        [
          7
        ],
        [
          11
        ],
        [
          15
        ],
        [
          14
        ],
        [
          13
        ],
        [
          12
        ],
        [
          8
        ],
        [
          4
        ]
      ]
    }
  },
  {
    "name": "dual-ring-5",
    "color": "blue",
    "animation": null,
    "shelf": "premium",
    "pattern": {
      "size": 5,
      "rows": null,
      "cols": null,
      "interval": 110,
      "frames": [
        [
          0,
          6
        ],
        [
          1,
          11
        ],
        [
          2,
          16
        ],
        [
          3,
          17
        ],
        [
          4,
          18
        ],
        [
          9,
          13
        ],
        [
          14,
          8
        ],
        [
          19,
          7
        ],
        [
          24,
          6
        ],
        [
          23,
          11
        ],
        [
          22,
          16
        ],
        [
          21,
          17
        ],
        [
          20,
          18
        ],
        [
          15,
          13
        ],
        [
          10,
          8
        ],
        [
          5,
          7
        ]
      ]
    }
  },
  {
    "name": "vortex-in",
    "color": "blue",
    "animation": null,
    "shelf": "premium",
    "pattern": {
      "size": 4,
      "rows": null,
      "cols": null,
      "interval": 90,
      "frames": [
        [
          0
        ],
        [
          1
        ],
        [
          2
        ],
        [
          3
        ],
        [
          7
        ],
        [
          11
        ],
        [
          15
        ],
        [
          14
        ],
        [
          13
        ],
        [
          12
        ],
        [
          8
        ],
        [
          4
        ],
        [
          5
        ],
        [
          6
        ],
        [
          10
        ],
        [
          9
        ]
      ]
    }
  },
  {
    "name": "col-wave-5",
    "color": "crimson",
    "animation": null,
    "shelf": "premium",
    "pattern": {
      "size": 5,
      "rows": null,
      "cols": null,
      "interval": 120,
      "frames": [
        [
          0,
          5,
          10,
          15,
          20
        ],
        [
          1,
          6,
          11,
          16,
          21
        ],
        [
          2,
          7,
          12,
          17,
          22
        ],
        [
          3,
          8,
          13,
          18,
          23
        ],
        [
          4,
          9,
          14,
          19,
          24
        ],
        [
          3,
          8,
          13,
          18,
          23
        ],
        [
          2,
          7,
          12,
          17,
          22
        ],
        [
          1,
          6,
          11,
          16,
          21
        ]
      ]
    }
  },
  {
    "name": "swell-roll",
    "color": "crimson",
    "animation": null,
    "shelf": "premium",
    "pattern": {
      "size": 4,
      "rows": null,
      "cols": null,
      "interval": 160,
      "frames": [
        [
          2,
          5,
          6,
          7,
          8,
          9,
          12
        ],
        [
          3,
          4,
          6,
          7,
          9,
          10,
          13
        ],
        [
          0,
          4,
          5,
          7,
          10,
          11,
          14
        ],
        [
          1,
          4,
          5,
          6,
          8,
          11,
          15
        ]
      ]
    }
  },
  {
    "name": "rain-4",
    "color": "crimson",
    "animation": null,
    "shelf": "premium",
    "pattern": {
      "size": 4,
      "rows": null,
      "cols": null,
      "interval": 180,
      "frames": [
        [
          0,
          5,
          10,
          15
        ],
        [
          4,
          9,
          14,
          3
        ],
        [
          8,
          13,
          2,
          7
        ],
        [
          12,
          1,
          6,
          11
        ]
      ]
    }
  },
  {
    "name": "tide-roll",
    "color": "blue",
    "animation": null,
    "shelf": "premium",
    "pattern": {
      "size": 4,
      "rows": null,
      "cols": null,
      "interval": 180,
      "frames": [
        [
          0,
          1,
          2,
          3
        ],
        [
          4,
          5,
          6,
          7
        ],
        [
          8,
          9,
          10,
          11
        ],
        [
          12,
          13,
          14,
          15
        ],
        [
          8,
          9,
          10,
          11
        ],
        [
          4,
          5,
          6,
          7
        ]
      ]
    }
  },
  {
    "name": "billboard-tiles",
    "color": "crimson",
    "animation": null,
    "shelf": "premium",
    "pattern": {
      "size": 4,
      "rows": null,
      "cols": null,
      "interval": 180,
      "frames": [
        [
          0,
          5,
          10,
          15
        ],
        [
          1,
          4,
          11,
          14
        ],
        [
          2,
          7,
          8,
          13
        ],
        [
          3,
          6,
          9,
          12
        ],
        [
          5,
          6,
          9,
          10
        ]
      ]
    }
  },
  {
    "name": "ripple-out",
    "color": "hotpink",
    "animation": null,
    "shelf": "premium",
    "pattern": {
      "size": 3,
      "rows": null,
      "cols": null,
      "interval": 260,
      "frames": [
        [
          4
        ],
        [
          1,
          3,
          5,
          7
        ],
        [
          0,
          2,
          6,
          8
        ]
      ]
    }
  }
];
